# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post_table',
        ),
    ]
